### ISSUE TITLE
Detect and warn about Smart Quotes

### ISSUE THREAD

**Issue by karlkeefer** [alexmojaki/futurecoder#342] opened 2022-04-30 19:41 UTC
I've encountered a few people who got stuck very early on because macOS was converting their single-quotes into `lsquo;` and `rsquo;` which reports a relevant error:
```
I suspect that you used a fancy unicode quotation mark
whose name is LEFT SINGLE QUOTATION MARK
```

But as beginners they had no idea why that was happening or how to disable it.

Maybe this kind of case can be detected to provide guidance around disabling smart quotes.

Or more controversially you could auto-replace them with single-quotes, since this is beginner-oriented and SmartQuotes will nearly always be unintended behavior.

**Comment by alexmojaki** [comment] 2022-05-01 09:58
Hi, thanks for the feedback!

> I've encountered a few people

I'm curious what you mean by this. Are you a teacher?

> Maybe this kind of case can be detected to provide guidance around disabling smart quotes.

@aroberge this sounds like a decent suggestion to expand the message in friendly-traceback.

> Or more controversially you could auto-replace them with single-quotes, since this is beginner-oriented and SmartQuotes will nearly always be unintended behavior.

Maybe. There might also be a way to prevent them from being inserted in the first place. But I don't have a Mac, I can't reproduce this on Browserstack, so I can't test a fix myself. Are you able to reproduce this? Could you test an attempted fix? Do you know if it happens in the editor, the shell, or both?

**Comment by aroberge** [comment] 2022-05-01 10:41
@karlkeefer The explanation you quote is generated by friendly-traceback which analyzes code **after** a Python traceback is generated. friendly-traceback works in various environments (Jupyter notebooks, terminals, editors like MU and IDLE, etc.) including sites like futurecoder.io.  

I included the extra information in friendly-traceback about the type of quotes used based on comments about people copy-pasting code from a text editor (like MS Word) into a Python console. However, sometimes it is caused by using the quote characters that are standard on a keyboard such as the one used by French users, as shown in this example (screenshot taken a few years ago, when I added "hints"):
![](https://raw.githubusercontent.com/aroberge/friendly/master/why_1.png)
I have no way to way to determine how the wrong types of quotes were entered, whether it was done by copy-pasting code or by typing on a keyboard; all I can do is detect them after the fact. Furthermore, when used within futurecoder, friendly-traceback would have no way to determine what OS is used or what is the user's locale. [@alexmojaki: I consider that attempting to offer guidance as to how to disable smart quotes without knowing the specific context in which they were entered would be an hopeless task.]

So, I am afraid that just pointing out that the wrong type of quote was used is the best I can hope to do with friendly-traceback.  Hopefully, the information provided by friendly-traceback is an improvement over the message provided by Python when this type of error occurs.

Preventing this type of problems from occurring in futurecoder is also going to be a challenge. I am not convinced that replacing smart quotes automatically is the right solution either, as beginners used to entering those quotes using their keyboard would be baffled by normal traceback generated by Python if they were to write the same code (as they have learned to do it on futurecoder) in a different environment than futurecoder. _Why does it not work now when it did before?..._

Perhaps the solution is to include a preliminary lesson about what quotes to use with Python, including warnings about smart quotes.

**Comment by alexmojaki** [comment] 2022-05-01 10:56
> I consider that attempting to offer guidance as to how to disable smart quotes without knowing the specific context in which they were entered would be an hopeless task.

I think it would be reasonable and harmless to make the message longer so that it has some chance of helping even if you don't know whether it will, e.g.

> If you copied from a program such as MS Word, check if ...
> If you are using a Mac, check if ...

Linking to an external page could limit the message length if that becomes an issue somehow.

Of course, the type of quote also provides some information, e.g. I'm guessing Mac doesn't automatically transform `"` into the French style of quotes?

**Comment by aroberge** [comment] 2022-05-01 11:28
This is the information currently given:
```
  Code block [1], line 1
    print(‘hello’)
          ^
SyntaxError: invalid character '‘' (U+2018)

        Did you mean to use a normal quote character, `'` or `"`?

    A `SyntaxError` occurs when Python cannot understand your code.

    Python could not understand the code in the code block [1]
    at the location indicated.

       1: print(‘hello’)
                ^

    Did you use copy-paste?
    Python indicates that you used the unicode character `‘`
    which is not allowed.
    I suspect that you used a fancy unicode quotation mark
    whose name is LEFT SINGLE QUOTATION MARK
    instead of a normal single or double quote for a string.
```
As you can see, it contains a lot more information than the part of the sentence that what was included in the original bug report. 

> Of course, the type of quote also provides some information, e.g. I'm guessing Mac doesn't automatically transform " into the French style of quotes?

I believe that these quotes are the default on the French OSX version; I could be wrong.  But it gets more complex than this.

The following page contains a sample of various "smart quotes", including a list of which ones are used in different countries: https://unicode-table.com/en/sets/quotation-marks/.  Many international keyboards do not include by default the "normal" single and double-quote found in the ASCII set; programmers have to learn some key-combinations or how to change keyboard configuration to access the relevant symbols.  

> Linking to an external page could limit the message length if that becomes an issue somehow.

As you know, friendly-traceback aims to provide information in various languages. Currently, it has complete or partial support for English, French, Spanish, Italian, Hebrew; I have received some translations for Russian just a few days ago.  I want to have everything "self-contained", without having to either maintain a dedicated website (asking translators to translate information there as well), or having to "chase" relevant websites for each language supported. Perhaps when friendly-traceback reaches version 1.0 (complete support of all exceptions found/generated by the standard library) I will consider such enhancement.

**Comment by karlkeefer** [comment] 2022-05-01 18:01
I think the suggestion of expanding the tutorial text to indicate some common cases that might break single quotes could do the trick. E.g.
> if you get a syntax error, you may need to change your keyboard layout to include single quotes, or you may need to disable SmartQuotes if you are on a Mac.

I shared this resource in a Slack environment with a couple hundred users and saw some get stuck with this syntax error. The traceback message was super useful for me as a programmer to know what was going on, but for a beginner it was still totally unclear how/what to change to fix it. Strings come early enough in the tutorial (step 3? 4?) that I think without my support they would have just stopped right there.

**Comment by alexmojaki** [comment] 2022-05-01 18:08
Do you have a Mac? Can you reproduce the issue?

**Comment by karlkeefer** [comment] 2022-05-01 18:10
I do not, but my wife does and I could borrow her computer if we need someone to test a change.

**Comment by alexmojaki** [comment] 2022-05-01 18:11
Can you check if the problem currently occurs in the editor and/or the shell?

**Comment by alexmojaki** [comment] 2022-05-18 13:46
OK I'm hoping that this was a shell-only issue that is fixed now by https://github.com/alexmojaki/futurecoder/commit/c50b312e565ea178646bba7a14352c08c2333f51, please let me know if it's not.

**Closed by alexmojaki** 2022-05-18 13:46 UTC

**Comment by karlkeefer** [comment] 2022-07-30 19:37
I finally had a chance to borrow another max with smartquotes enabled - no issues in the tutorial or straight to the shell!
Thanks again for the patch!
